tpi-rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :professionals do
    resources :appointments do 
      collection do 
        delete 'destroy_all', action: "destroy_all"
      end
    end
  end
  post 'professionals/grilla_day', to: "appointments#grilla_day"
  post 'professionals/grilla_week', to: "appointments#grilla_week" 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'professionals#index'
end

tpi-rails/app/models/professional.rb
class Professional < ApplicationRecord
    has_many :appointments
    validates :name, :surname, presence: true, length: { maximum: 30 }
    validates :name, uniqueness: {
        scope: :surname,
        message: "Ya existe este profesional" }
        
    def grilla(date)
        turno= self.appointments.select{ | appointment | appointment.date==date }.first
        if turno.nil?
            "No hay turno"
        else
            "#{turno.surname} #{turno.name}"
        end
    end
end

tpi-rails/app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: %i[ show edit update destroy ]

  # GET /professionals or /professionals.json
  def index
    @professionals = Professional.all.reorder('surname, name')
  end

  # GET /professionals/1 or /professionals/1.json
  def show
  end

  # GET /professionals/new
  def new
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
  end

  # POST /professionals or /professionals.json
  def create
    @professional = Professional.new(professional_params)

    respond_to do |format|
      if @professional.save
        format.html { redirect_to @professional, notice: "Professional was successfully created." }
        format.json { render :show, status: :created, location: @professional }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professionals/1 or /professionals/1.json
  def update
    respond_to do |format|
      if @professional.update(professional_params)
        format.html { redirect_to @professional, notice: "Professional was successfully updated." }
        format.json { render :show, status: :ok, location: @professional }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professionals/1 or /professionals/1.json
  def destroy
    begin
    @professional.destroy
    respond_to do |format|
      format.html { redirect_to professionals_url, notice: "Professional was successfully destroyed." }
      format.json { head :no_content }
    end
    rescue
      respond_to do |format|
        format.html { redirect_to professionals_url, notice: "Destroy appointments before eliminate a professional." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional
      @professional = Professional.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professional_params
      params.require(:professional).permit(:surname, :name)
    end
end

tpi-rails/app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

tpi-rails/app/views/professionals/_form.html.erb
<%= form_with(model: professional) do |form| %>
  <% if professional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professional.errors.count, "error") %> prohibited this professional from being saved:</h2>

      <ul>
        <% professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tpi-rails/app/views/professionals/edit.html.erb
<h1>Editing Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Show', @professional %> |
<%= link_to 'Back', professionals_path %>

tpi-rails/app/views/professionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professionals</h1>

<table border=1>
  <thead>
    <tr>
      <th>Surname</th>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @professionals.each do |professional| %>
      <tr>
        <td><%= professional.surname %></td>
        <td><%= professional.name %></td>
        <td><%= link_to 'Show', professional %></td>
        <% if can? :update, @professional %>
          <td><%= link_to 'Edit', edit_professional_path(professional) %></td>
        <% end %>
        <% if can? :delete, @professional %>
          <td><%= link_to 'Destroy', professional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= link_to 'Show Appointments', professional_appointments_path(professional) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Professional %>
  <%= link_to 'New Professional', new_professional_path %>
<% end %>

<%= render 'appointments/grilla',professional:nil %>

tpi-rails/app/views/professionals/new.html.erb
<h1>New Professional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Back', professionals_path %>

tpi-rails/app/views/professionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @professional.surname %>
</p>

<p>
  <strong>Name:</strong>
  <%= @professional.name %>
</p>

<%= link_to 'Edit', edit_professional_path(@professional) %> |
<%= link_to 'Back', professionals_path %>