tpi-rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :professionals do
    resources :appointments do 
      collection do 
        delete 'destroy_all', action: "destroy_all"
      end
    end
  end
  post 'professionals/grilla_day', to: "appointments#grilla_day"
  post 'professionals/grilla_week', to: "appointments#grilla_week" 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'professionals#index'
end

tpi-rails/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional
  validates :date, :name, :surname, :phone, :professional_id, presence: true
  validates :name, :surname, length: { maximum: 30 }
  validates :phone, numericality:{
    only_integer: true}
  validates_date :date, on_or_after: lambda {DateTime.tomorrow}, on_or_after_message: "Solicite un turno a partir de mañana"
  validates :date, uniqueness: {
    scope: :professional_id,
    message: "Este turno ya no esta disponible" } 
end

tpi-rails/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]
  before_action :set_professional, only: %i[ show edit update destroy destroy_all index new create ]
  before_action :week_calendar, only: %i[ grilla_week ]
  # GET /appointments or /appointments.json
  def index
    @appointments = Professional.find(params[:professional_id]).appointments.reorder('date')
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to professional_appointments_path(@professional.id), notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to professional_appointments_path(@professional), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to professional_appointments_path(@professional.id), notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Appointment.where(professional_id: @professional.id).destroy_all
    respond_to do |format|
      format.html { redirect_to professional_appointments_path(@professional.id), notice: "Los turnos han sido cancelado." }
      format.json { head :no_content }
    end
  end

  def grilla_day
    erb= ERB.new(File.read("./app/views/appointments/grilla_day.html.erb"))
    date= DateTime.parse("#{(params["date(1i)".to_sym])}-#{(params["date(2i)".to_sym])}-#{(params["date(3i)".to_sym])}_08:00")
    dateEnd= DateTime.parse(date.strftime("%F_18:00"))
    if (params[:professional_id]) == ""
      appointments= Appointment.where('date BETWEEN ? AND ?', date, dateEnd).reorder('date')
      output= erb.result_with_hash(appointments:appointments, date:date, professional:nil)
    title= "#{date.strftime("%F")}.html"
    else
      professional= Professional.find(params[:professional_id])
      appointments= professional.appointments.where('date BETWEEN ? AND ?', date, dateEnd).reorder('date')
      output= erb.result_with_hash(appointments:appointments, date:date, professional:professional)
      title= "#{professional.surname}-#{professional.name}-#{date.strftime("%F")}.html"
    end  
    send_data(output, :filename =>title)
  end

  def grilla_week
    erb= ERB.new(File.read("./app/views/appointments/grilla_week.html.erb"))
    if (params[:professional_id]) == ""
      professionals= Professional.joins(:appointments).where('appointments.date BETWEEN ? AND ?', (@date), (@dateEnd)).group('professionals.id')
      output= erb.result_with_hash(professionals:professionals, date:@date, professional:nil)
      title= "week-#{@date.strftime("%F")}.html"
    else
      professional= Professional.find(params[:professional_id])
      professionals= [professional]
      output= erb.result_with_hash(professionals:professionals, date:@date, professional:professional)  
      title= "#{professional.surname}-#{professional.name}-week-#{@date.strftime("%F")}.html"
    end
    send_data(output, :filename =>title)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :surname, :name, :phone, :notes, :professional_id)
    end

    def set_professional
      @professional = Professional.find(params[:professional_id])  
    end

    def week_calendar
      @date = DateTime.parse("#{(params["date(1i)".to_sym])}-#{(params["date(2i)".to_sym])}-#{(params["date(3i)".to_sym])}_08:00")  
      case @date.strftime("%A")
        when "Sunday"
          @date
        when "Monday"
          @date= @date-1
        when "Tuesday"
          @date= @date-2
        when "Wednesday"
          @date= @date-3
        when "Thursday"
          @date= @date-4
        when "Friday"
          @date= @date-5
        when "Saturday"
          @date= @date-6
      end
      @dateEnd= @date + 6
      @dateEnd= DateTime.parse(@dateEnd.strftime("%F_18:00"))
    end
end

tpi-rails/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

tpi-rails/app/views/appointments/_form.html.erb
<%= form_with(model: appointment, url:[@professional, appointment]) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, :start_year => DateTime.now.year, :end_year => DateTime.now.year + 10, :start_hour => 8, :end_hour => 18, :minute_step => 30 %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>
  
  <div class="field">
    <%= form.hidden_field :professional_id, :value => @professional.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tpi-rails/app/views/appointments/_grilla.html.erb
<%= form_with(model: nil, url:  professionals_grilla_day_path) do |form| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <% if professional.nil? %>
    <%= form.hidden_field :professional_id, :value => professional %>
    <% else %>
    <div class="field">
    <%= form.hidden_field :professional_id, :value => professional.id %>
    </div> 
    <% end %> 
    <div class="field">
        <%= form.label :date, "Fecha de la grilla" %>
        <%= form.date_select :date, :start_year => DateTime.now.year, :end_year => DateTime.now.year + 10 %>
    </div>

    <div class="actions">
        <%= form.submit "grilla diaria", data: { disable_with: false } %>
    </div>

    <div class="actions">
        <%= form.submit "grilla semanal", data: { disable_with: false }, formaction: professionals_grilla_week_path  %>
    </div>
<% end %>

tpi-rails/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment, professional: @professional %>

<%= link_to 'Show', professional_appointment_path(@professional, @appointment) %> |
<%= link_to 'Back', professional_appointments_path(@professional) %>

tpi-rails/app/views/appointments/grilla_day.html.erb
<div>
    <% if professional.nil? %>
    <h2>
        turnos del dia <%="#{date.strftime("%F")}" %>
    </h2>
    <% else %>
    <h2>
        turnos del dia <%="#{date.strftime("%F")} del profesional #{professional.surname} #{professional.name}"%>
    </h2>
    <% end %>
    <table border=1>
        <thead>
            <tr>
                <th>
                    hora
                </th>
                <% if professional.nil? %>
                <th>
                    profesional
                </th>
                <% end %>
                <th>
                    nombre del paciente
                </th>
                <th>
                    apellido del paciente                
                </th>
                <th>
                    telefono
                </th>
            </tr>
        </thead>
        <tbody>
            <%appointments.each do | appointment |%>
                <tr>

                    <td>
                        <%= appointment.date.strftime("%R") %>
                    </td>
                    <% if professional.nil? %>
                        <td>
                            <%= "#{appointment.professional.surname} #{appointment.professional.name}" %>
                        </td>
                    <% end %>
                    <td>
                        <%= appointment.name %>                        
                    </td>

                    <td>
                        <%= appointment.surname %>                        
                    </td>

                    <td>
                        <%= appointment.phone %>                        
                    </td>
                </tr>
            <%end%>    
        </tbody>
    </table>
</div>

tpi-rails/app/views/appointments/grilla_week.html.erb
<div>
    <% if professional.nil? %>
    <h2>
        turnos de la semana <%="#{date.strftime("%F")}" %>
    </h2>
    <% else %>
    <h2>
        turnos de la semana <%="#{date.strftime("%F")} del profesional #{professional.surname} #{professional.name}"%>
    </h2>
    <% end %>
    <table border=1>
        <thead>
            <tr>
                <th>
                    hora
                </th>
                <% if professional.nil? %>
                <th>
                    profesional
                </th>
                <% end %>
                <th>
                    domingo
                </th>
                <th>
                    lunes               
                </th>
                <th>
                    martes
                </th>
                <th>
                    miercoles
                </th>
                <th>
                    jueves
                </th>
                <th>
                    viernes
                </th>
                <th>
                    sabado
                </th>
            </tr>
        </thead>
        <tbody>
            <% new_date= date %>
            <% while !(new_date.hour == 18) || !(new_date.min == 30)
                 professionals.each do | p | %>
                    <tr>
                        <td>
                            <%= new_date.strftime("%R") %>
                        </td>
                        <% if professional.nil? %>
                            <td>
                                <%= "#{p.surname} #{p.name}" %>
                            </td>
                        <% end %>
                        <td>
                            <%= p.grilla(new_date) %>
                        </td>
                        <td>
                            <%= p.grilla(new_date+1) %>
                        </td>
                        <td>
                            <%= p.grilla(new_date+2) %>
                        </td>
                        <td>
                            <%= p.grilla(new_date+3) %>
                        </td>
                        <td>
                            <%= p.grilla(new_date+4) %>
                        </td>
                        <td>
                            <%= p.grilla(new_date+5) %>
                        </td>
                        <td>
                            <%= p.grilla(new_date+6) %>
                        </td>
                    </tr>
                <% end 
                new_date= new_date + (30/1440.0) %>
            <% end %>
        </tbody>
    </table>
</div>

tpi-rails/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments <%= "#{@professional.surname} #{@professional.name}" %> </h1>

<table border=1>
  <thead>
    <tr>
      <th>Date</th>
      <th>Surname</th>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date.strftime("%F_%R") %></td>
        <td><%= appointment.surname %></td>
        <td><%= appointment.name %></td>
        <td><%= appointment.phone %></td>
        <td><%= link_to 'Show', professional_appointment_path(@professional, appointment) %></td>
        <% if can? :update, appointment %>
          <td><%= link_to 'Edit', edit_professional_appointment_path(@professional, appointment) %></td>
        <% end %>
        <% if can? :delete, appointment %>
          <td><%= link_to 'Destroy', professional_appointment_path(@professional, appointment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Appointment %>
  <%= link_to 'New Appointment', new_professional_appointment_path(@professional) %>
<% end %>
<% if can? :delete, Appointment %>
  <td><%= link_to 'Destroy All', destroy_all_professional_appointments_path(@professional), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

<%= render 'appointments/grilla', professional:@professional %>

tpi-rails/app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', professional_appointments_path %>

tpi-rails/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date.strftime("%F_%R") %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @appointment.surname %>
</p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @appointment.phone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<p>
  <strong>Professional:</strong>
  <%= "#{@appointment.professional.surname} #{@appointment.professional.name}"  %>
</p>

<%= link_to 'Edit', edit_professional_appointment_path(@professional, @appointment) %> |
<%= link_to 'Back', professional_appointments_path(@professional)%>